### ISSUE TITLE
Visualization shows a blank white screen

### ISSUE THREAD

**Issue by ktkarhu** [aalto-trafficsense/regular-routes-server#13]
Is server up and running?

**Comment by Gekkio** [comment]
It's up but at least some visualization queries time out. Either we have too much data for the server to handle, or some recent change has killed the performance.

**Comment by finnlander** [comment]
We have ~1.48 million location data entries and ~68k activity data entries. Do we need index for that activity_data -table? I think that location data table already has indexed the data. Right?

**Comment by ktkarhu** [comment]
Usually it makes sense to add an index for those columns that are in the WHERE part of the query that fetches data for visualization request (i.e. device token or visualization ID (which ever you use) and date)

If you can figure out the actual queries that time out, that would help to add possible missing indexes.

BTW, even though the visualization is not working currently, is data being collected?
