### ISSUE TITLE
Some problems with snapping

### ISSUE THREAD

**Issue by ktkarhu** [aalto-trafficsense/regular-routes-server#14]
See April 1st of device 60: http://regularroutes.niksula.hut.fi/api/visualize/60
- Why there are several waypoints missing in Kehä III?
- What are the not connected waypoints in Kehä III towards Vihdintie (120) and Hämeenlinnan väylä (E12/3)?

**Comment by Gekkio** [comment]
There's several roads with type "trunk_link" that is not included in the current configuration, so these roads are completely missing from the data. No roads -> no waypoints

**Comment by ktkarhu** [comment]
Can you see any reason why not to add them? If not, then I would just add them.

**Comment by MJRinne** [comment]
Trunk links were added and waypoint generation on e.g. Ring III improved. I have another issue on the waypoints, but it's a bit different, so I'll open a new one and suggest to close this.
