### ISSUE TITLE
Snapping calls return a gateway timeout

### ISSUE THREAD

**Issue by MJRinne** [aalto-trafficsense/regular-routes-server#17]
Some demo effect today - calling:

http://regularroutes.niksula.hut.fi/api/maintenance/snapping

Consistently (tried ~5 times) returns:

504 Gateway Time-out
nginx/1.6.2

**Comment by ktkarhu** [comment]
still giving timeout ...

**Comment by finnlander** [comment]
I executed the snapping sql manually to the database (~180k points were snapped) -> now the interface call also seem to work. 

SQL execution took something between 30 and 60 seconds and therefore I suspect that the call has same performance-related timeout occurring.
