### ISSUE TITLE
Snapping always returns 20,000 points

### ISSUE THREAD

**Issue by MJRinne** [aalto-trafficsense/regular-routes-server#18]
Latest update to snapping limited the amount of points snapped at once to 20,000 points. I tested running snapping consecutively about 20 times, still 20,000 points are returned each time. Snapping the 20,000 points takes some time with each call (i.e. doesn't look like only the return value is wrong).

It would appear that the snapped points are not saved and the same 20k points are snapped every time, but this is speculation only.

Steps to repeat:

Call `http://regularroutes.niksula.hut.fi/api/maintenance/snapping`

What is returned:

```
Snapping was done to 20000 data points
```

What was expected to be returned:

After repeated calls the number should go below 20000.

**Comment by Gekkio** [comment]
This was caused by the crossings update and snappings reset. The total amount of points is around 950 000, and even after running the snapping 20-30 times, there was still more than 400 000 unsnapped points. I snapped these manually, so all points are now up to date.
