### ISSUE TITLE
Global statistics get calculated twice when scheduler is running

### ISSUE THREAD

**Issue by MJRinne** [aalto-trafficsense/regular-routes-server#32]
When the scheduler runs the nightly execution, it calculates as many new rows as needed into the `global_statistics` table. However, when running nightly, a re-execution adds both the previous day and the day before. As a result:
- When scheduler is running, each day appears twice
- The latest day only appears once until the next night adds the duplicate

Below is an example. Until 6.1. scheduler was not running. Today is 19.1., so 18.1. appears only once, but tonight it will be added again.

57 | 2016-01-04 00:00:00 |  94.7517334863192 |                             1 | 25.6171089095973
 58 | 2016-01-05 00:00:00 |  111.919054918592 |                             2 | 41.3713384015266
 59 | 2016-01-06 00:00:00 |                33 |                             2 | 4.03792166385355
 60 | 2016-01-06 00:00:00 |                33 |                             2 | 4.03792166385355
 61 | 2016-01-07 00:00:00 |  137.308002982029 |                             5 |  171.52291021883
 62 | 2016-01-07 00:00:00 |  137.308002982029 |                             5 |  171.52291021883
 63 | 2016-01-08 00:00:00 |  130.503037958274 |                             5 | 136.108097784657
 64 | 2016-01-08 00:00:00 |  130.503037958274 |                             5 | 136.108097784657
 65 | 2016-01-09 00:00:00 |  126.066048372366 |                             6 | 230.714412838902
 66 | 2016-01-09 00:00:00 |  126.066048372366 |                             6 | 230.714412838902
 67 | 2016-01-10 00:00:00 |  142.140644739844 |                             6 | 327.033446062617
 68 | 2016-01-10 00:00:00 |  142.140644739844 |                             6 | 327.033446062617
 69 | 2016-01-11 00:00:00 |  128.400071617545 |                             6 | 219.367105711376
 70 | 2016-01-11 00:00:00 |  128.400071617545 |                             6 | 219.367105711376
 71 | 2016-01-12 00:00:00 |  129.369688438695 |                             6 | 161.584384206671
 72 | 2016-01-12 00:00:00 |  129.369688438695 |                             6 | 161.584384206671
 73 | 2016-01-13 00:00:00 |  137.695768860356 |                             6 | 195.798364242481
 74 | 2016-01-13 00:00:00 |  137.695768860356 |                             6 | 195.798364242481
 75 | 2016-01-14 00:00:00 |  134.035001602688 |                             6 | 200.980842986074
 76 | 2016-01-14 00:00:00 |  134.035001602688 |                             6 | 200.980842986074
 77 | 2016-01-15 00:00:00 |  129.208783616546 |                             6 | 151.676164562667
 78 | 2016-01-15 00:00:00 |  129.208783616546 |                             6 | 151.676164562667
 79 | 2016-01-16 00:00:00 |  65.8908866212735 |                             6 | 34.3277950525675
 80 | 2016-01-16 00:00:00 |  65.8908866212735 |                             6 | 34.3277950525675
 81 | 2016-01-17 00:00:00 |  143.993407696272 |                             6 | 89.9442279493334
 82 | 2016-01-17 00:00:00 |  143.993407696272 |                             6 | 89.9442279493334
 83 | 2016-01-18 00:00:00 |  101.648678615237 |                             6 |  93.737295018304

**Comment by ttolv** [comment]
Yep it was starting on max(time) from global_statistics instead of the next day. fixed 15f722e
