### ISSUE TITLE
Filtered activity changes later than expected.

### ISSUE THREAD

**Issue by MJRinne** [aalto-trafficsense/regular-routes-server#34]
Observed by Mehrdad, recorded Fri March 11th 2016. These are the original recorded points:
![image](https://cloud.githubusercontent.com/assets/1104150/13749599/deefaf0a-ea0a-11e5-8bbf-7f972934080e.png)

Filtered points:
![image](https://cloud.githubusercontent.com/assets/1104150/13749569/c4927638-ea0a-11e5-9bd9-d7f1c49d5be8.png)

The filtered transition from on_foot (green) to in_vehicle (red) is expected to happen at the median point between the last good batch of n points of on_foot and the first good batch of n points of in_vehicle. 

Now it looks like the transition takes place only at the beginning of the first good batch of n samples of in_vehicle, which is significantly later.

**Comment by MJRinne** [comment]
The case should be checked in more detail from the data: It could also be that the crossing (traffic lights) has so many overlapping points that the operation is still correct, even though it looks a bit unexpected in the visualisation.

**Comment by ttolv** [comment]
Tested with current summed activity window stage (merge 15f4f0e ), this case behaves now:
![screen shot 2016-07-06 at 16 00 45](https://cloud.githubusercontent.com/assets/18309777/16618644/084526b4-4393-11e6-81f0-ca988ea02b05.png)
