### ISSUE TITLE
Export of user's own data (MyData)

### ISSUE THREAD

**Issue by tuukka** [aalto-trafficsense/regular-routes-server#38]
Would it be easy for you to add (raw) data export as GeoJSON and/or gpx? This could work like the current CSV export but include the raw data points.

**Comment by ttolv** [comment]
Should be easy enough, it already speaks geojson to the client and gmaps. Guess there's two cases of interest: A) dump raw trace sent from user's terminals; B) get the path with processed modes and detections with possibly simplified geometry.

The raw case (A) has some edges like users with multiple terminals reporting concurrently, that isn't handled at that level.

The processed path (B) should be just a matter of light refactor, route, link params

**Comment by ttolv** [comment]
Pardon the lag... resurrected that branch, the trips view https://regularroutes.niksula.hut.fi/trips now has a geojson link, which emits the same geojson that the client gets — post activity and bogus-location cleanup. There are some extra arguments that can be used,
maxpts — maximum points within each linestring, more geometrically redundant points will be excluded, default all
mindist — metres off path contributed by each point, more geometrically redundant points will be excluded, default 0
exclude — exclude legs of particular mode, comma separated, default STILL

**Comment by tuukka** [comment]
Thanks - works nicely!
